### ISSUE TITLE
[S1-PBI2] Membuat fitur register

### ISSUE THREAD

**Issue by figosyanan** [SI-RPL-2023/SI4407_KEL4_Threadly#1]

**Comment by figosyanan** [comment]
![Image](https://user-images.githubusercontent.com/126429015/228451044-d2f5d4ad-a142-4c48-ab9d-ad6886e559aa.png)

**Comment by dani-rdhn** [comment]
![Image](https://github.com/SI-RPL-2023/SI4407_KEL4_Threadly/assets/109774035/97714d22-7522-4a31-954e-a16c3216413b)
