### ISSUE TITLE
[S1-PBI3] Membuat tampilan halaman utama dengan berbagai fitur

### ISSUE THREAD

**Issue by figosyanan** [SI-RPL-2023/SI4407_KEL4_Threadly#2]
Saya sebagai pengguna, ingin melihat halaman awal untuk melihat fitur-fitur yang tersedia

**Comment by suffyAuroraa** [comment]
![Image](https://user-images.githubusercontent.com/126407840/228451865-213cc52c-e92b-412f-9449-5f603f7269a1.png)

**Comment by suffyAuroraa** [comment]
![Image](https://user-images.githubusercontent.com/126407840/228453190-99a0da50-003b-4823-a794-e2bfcff0706e.png)

**Comment by suffyAuroraa** [comment]
![Image](https://user-images.githubusercontent.com/126407840/228453562-eb11ef30-eb69-4fb9-a1c1-fdfcc77b2fcf.png)
