### ISSUE TITLE
[S1-PBI4] Membuat profile yang dapat diedit

### ISSUE THREAD

**Issue by figosyanan** [SI-RPL-2023/SI4407_KEL4_Threadly#3]

**Comment by dani-rdhn** [comment]
![Image](https://user-images.githubusercontent.com/109774035/228451537-cf8e8208-1b0f-40bb-9fbe-e6aa84eba2eb.png)

**Comment by dani-rdhn** [comment]
![Image](https://user-images.githubusercontent.com/109774035/228452170-5ff07f6d-a2fd-4c5c-843f-1a2dd48453c6.png)
