### ISSUE TITLE
[S1-PBI5] Membuat artikel produk

### ISSUE THREAD

**Issue by figosyanan** [SI-RPL-2023/SI4407_KEL4_Threadly#4]

**Comment by IchsanFznrdi** [comment]
![Image](https://user-images.githubusercontent.com/115572007/228452190-5d8a6434-3647-4ecd-8609-9414260912d8.png)

**Comment by IchsanFznrdi** [comment]
![Image](https://user-images.githubusercontent.com/115572007/228452923-3ce392da-f473-4671-b087-7aa7f46319e9.png)

**Comment by IchsanFznrdi** [comment]
![Image](https://user-images.githubusercontent.com/115572007/228453983-2a01cade-0a2e-448d-8d69-cc4204a780a9.png)
