### ISSUE TITLE
[S3-PBI13] Membuat pencarian produk

### ISSUE THREAD

**Issue by figosyanan** [SI-RPL-2023/SI4407_KEL4_Threadly#5]

**Comment by THON123456** [comment]
![Image](https://user-images.githubusercontent.com/115631618/228453600-d66b3662-855a-4318-bb10-16673d75d6d0.png)

**Comment by THON123456** [comment]
![Image](https://user-images.githubusercontent.com/115631618/228454652-4d228f97-fce4-43a6-b3f2-1b47350a8bdf.png)

**Comment by THON123456** [comment]
![Image](https://user-images.githubusercontent.com/115631618/228455093-bf7f777e-1f0e-4e3c-be69-4ebf7f2e940c.png)
