### ISSUE TITLE
[S2-PBI9] Membuat kategori produk

### ISSUE THREAD

**Issue by figosyanan** [SI-RPL-2023/SI4407_KEL4_Threadly#6]
Saya sebagai pengguna, ingin dapat memilih produk berdasarkan kategori agar lebih mudah

**Comment by suffyAuroraa** [comment]
![Image](https://user-images.githubusercontent.com/126407840/228454344-9af902ee-f7ec-4b8d-8fcb-5725bcc25d96.png)

**Comment by suffyAuroraa** [comment]
![Image](https://user-images.githubusercontent.com/126407840/228454444-8c47c49b-b609-4ff0-967c-bc588491ad5c.png)

**Comment by suffyAuroraa** [comment]
![Image](https://user-images.githubusercontent.com/126407840/228454700-c42dee39-200f-4478-8e2a-5a27e754bea3.png)
